NetCoreLinkToSqlInject/Models/Coche.cs
namespace NetCoreLinkToSqlInject.Models
{
    public class Coche : ICoche
    {
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Imagen { get; set; }
        public int Velocidad { get; set; }
        public int VelocidadMax { get; set; }

        public Coche()
        {
            this.Marca = "Dodge";
            this.Modelo = "Viper";
            this.Imagen = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Aewroi.jpg/1200px-Aewroi.jpg";
            this.Velocidad = 0;
            this.VelocidadMax = 320;
        }

        public int Acelerar()
        {
            this.Velocidad += 20;
            if (this.Velocidad > VelocidadMax)
            {
                this.Velocidad = this.VelocidadMax;
            }
            return this.Velocidad;
        }

        public int Frenar()
        {
            this.Velocidad -= 20;
            if (this.Velocidad < 0)
            {
                this.Velocidad = 0;
            }
            return this.Velocidad;  
        }
    }
}

NetCoreLinkToSqlInject/Models/Deportivo.cs
namespace NetCoreLinkToSqlInject.Models
{
    public class Deportivo : ICoche
    {
        public Deportivo()
        {
            this.Marca = "Koenigsegg";
            this.Modelo = "Regera";
            this.Imagen = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Regera_%28light_gradient%29.png/1200px-Regera_%28light_gradient%29.png";
            this.Velocidad = 0;
            this.VelocidadMax = 400;
        }
        public string Marca { get ; set; }
        public string Modelo { get; set; }
        public string Imagen { get; set; }
        public int Velocidad { get; set; }
        public int VelocidadMax { get; set; }

        public int Acelerar()
        {
            this.Velocidad += 60;
            if (this.Velocidad > this.VelocidadMax)
            {
                this.Velocidad = this.VelocidadMax;
            }
            return this.Velocidad;
        }

        public int Frenar()
        {
            this.Velocidad -= 30;
            if (this.Velocidad < 0)
            {
                this.Velocidad = 0;
            }
            return this.Velocidad;
        }
    }
}

NetCoreLinkToSqlInject/Models/Doctor.cs
namespace NetCoreLinkToSqlInject.Models
{
    public class Doctor
    {
        public int HOSPITAL_COD { get; set; }
        public int DOCTOR_NO { get; set; }
        public string APELLIDO { get; set; }
        public string ESPECIALIDAD { get; set; }
        public int SALARIO { get; set; }
    }
}

NetCoreLinkToSqlInject/Models/ErrorViewModel.cs
namespace NetCoreLinkToSqlInject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NetCoreLinkToSqlInject/Models/Interface.cs
namespace NetCoreLinkToSqlInject.Models
{
    public interface ICoche
    {
        string Marca { get; set; }
        string Modelo { get; set; }
        string Imagen { get; set; }
        int Velocidad { get; set; }
        int VelocidadMax { get; set; }
        int Acelerar();
        int Frenar();
    }
}

NetCoreLinkToSqlInject/Controllers/CochesController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreLinkToSqlInject.Models;

namespace NetCoreLinkToSqlInject.Controllers
{
    public class CochesController : Controller
    {
        /*private Coche car;*/
        private ICoche car;

        public CochesController(ICoche car)
        {
            this.car = car;
        }

        public IActionResult Index()
        {
            return View(this.car);
        }

        [HttpPost]
        public IActionResult Index(string accion)
        {
            if(accion.ToLower() == "acelerar")
            {
                this.car.Acelerar();
            } else
            {
                this.car.Frenar();
            }
            return View(this.car);
        }
    }
}

NetCoreLinkToSqlInject/Controllers/DoctoresController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreLinkToSqlInject.Models;
using NetCoreLinkToSqlInject.Repositories;

namespace NetCoreLinkToSqlInject.Controllers
{
    public class DoctoresController : Controller
    {
        RepositoryDoctorOracle repo;

        public DoctoresController()
        {
            this.repo = new RepositoryDoctorOracle();
        }

        public IActionResult Index()
        {
            List<Doctor> doctores = this.repo.GetDoctores();
            return View(doctores);
        }
        public IActionResult Delete(int id)
        {
            this.repo.DeleteDoctor(id);
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Doctor doctor)
        {
            this.repo.InsertDoctor(doctor.HOSPITAL_COD, doctor.APELLIDO, doctor.ESPECIALIDAD, doctor.SALARIO);
            ViewData["MENSAJE"] = "Departamento insertado";
            /*return View("Index");*/
            return RedirectToAction("Index");
        }
    }
}

NetCoreLinkToSqlInject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreLinkToSqlInject.Models;
using System.Diagnostics;

namespace NetCoreLinkToSqlInject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NetCoreLinkToSqlInject/Views/Coches/Index.cshtml
@model ICoche


<h4>@Model.Marca, @Model.Modelo</h4>
<img src="@Model.Imagen" style="width:350px; height: 200px;" />

<h4 style="color:purple">Velocidad actual: @Model.Velocidad</h4>

<h4 style="color: crimson">Velocidad máxima: @Model.VelocidadMax</h4>

<form method="post">
    <button name="accion" value="acelerar" class="btn btn-outline-info">Acelerar</button>
    <button name="accion" value="frenar" class="btn btn-outline-danger">Frenar</button>
</form>

NetCoreLinkToSqlInject/Views/Doctores/Create.cshtml
<h4 class="mb-4">Create a new Doctor</h4>

<button class="btn btn-primary mb-4">
    <a asp-controller="Departamentos" asp-action="Index" class="link-dark">Volver a Index</a>
</button>

<form method="post" class="form">
    <label>Id Hospital</label>
    <input type="text" name="hospital_cod" class="form-control" required />
    <label>Apellido</label>
    <input type="text" name="apellido" class="form-control" required />
    <label>Especialidad</label>
    <input type="text" name="especialidad" class="form-control" required />
    <label>Salario</label>
    <input type="text" name="salario" class="form-control" required />
    <button class="btn btn-info">Create</button>
</form>

<h4>@ViewData["MENSAJE"]</h4>

NetCoreLinkToSqlInject/Views/Doctores/Index.cshtml
@model List<Doctor>

<h4 class="mb-4">Listado depts</h4>

<table class="table table-active table-bordered table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>HOSPITAL</th>
            <th>APELLIDO</th>
            <th>ESPECIALIDAD</th>
            <th>SALARIO</th>
            <th>ACTIONS</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Doctor doctor in Model)
        {
            <tr>
                <td>@doctor.DOCTOR_NO</td>
                <td>@doctor.HOSPITAL_COD</td>
                <td>@doctor.APELLIDO</td>
                <td>@doctor.ESPECIALIDAD</td>
                <td>@doctor.SALARIO</td>
                <td>
                    @*<button class="btn btn-warning">
                        @Html.ActionLink("Details", "Details", "Doctores", new { id = doctor.DOCTOR_NO})
                    </button>*@
                    <button class="btn btn-danger mx-auto">
                        @Html.ActionLink("Delete", "Delete", "Doctores", new { id = doctor.DOCTOR_NO})
                    </button>
                    @*<button class="btn btn-dark mx-auto">
                        @Html.ActionLink("Update", "Update", "Doctores", new { id = doctor.DOCTOR_NO})
                    </button>*@
                </td>
            </tr>
        }
    </tbody>
</table>

NetCoreLinkToSqlInject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NetCoreLinkToSqlInject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCoreLinkToSqlInject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetCoreLinkToSqlInject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetCoreLinkToSqlInject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coches" asp-action="Index">Coches</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctores" asp-action="Index">Doctores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctores" asp-action="Create">Nuevo Doctor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NetCoreLinkToSqlInject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>